name:                cubiml
version:             0.1.0.0
github:              ewilden/cubiml
license:             BSD3
author:              Evan Wildenhain
maintainer:          evan.wildenhain@gmail.com
copyright:           2020 Evan Wildenhain

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ewilden/cubiml#readme>

dependencies:
- base >= 4.11 && < 10
- mtl
- megaparsec
- microlens-platform
- parser-combinators
- raw-strings-qq
- rio >= 0.1.12.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cubiml-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - cubiml
    - optparse-simple
    - raw-strings-qq

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  cubiml-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - cubiml
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
